# Generated by Django 4.1.7 on 2023-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_studentsnew_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradelevel",
            name="is_deleted",
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name="gradelevelteacher",
            name="is_deleted",
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name="section",
            name="is_deleted",
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name="teachersnew",
            name="is_deleted",
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name="gradelevel",
            name="gradelevel_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="section",
            name="sectionname",
            field=models.CharField(max_length=250),
        ),
    ]
