# Generated by Django 4.1.7 on 2023-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_gradelevel_is_deleted_gradelevelteacher_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradelevel",
            name="is_deleted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gradelevelteacher",
            name="is_deleted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="section",
            name="is_deleted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentsnew",
            name="is_deleted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teachersnew",
            name="is_deleted",
            field=models.IntegerField(default=0),
        ),
    ]
