# Generated by Django 4.1.7 on 2023-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_gradelevel_gradelevel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradelevel",
            name="gradelevel_name",
            field=models.CharField(max_length=250),
        ),
    ]
