# Generated by Django 4.1.7 on 2023-04-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjects",
            name="is_deleted",
            field=models.BooleanField(default=0),
        ),
    ]
