# Generated by Django 4.1.7 on 2023-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_subjects_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjects",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
