# Generated by Django 4.1.7 on 2023-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_subjects_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="users.subjects"),
        ),
    ]
