# Generated by Django 4.1.7 on 2023-04-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_section_subjects"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GradeLevelTeacher",
        ),
    ]
