# Generated by Django 4.1.7 on 2023-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_delete_gradelevelteacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachersnew",
            name="subject",
        ),
        migrations.AddField(
            model_name="teachersnew",
            name="subject",
            field=models.ManyToManyField(blank=True, to="users.subjects"),
        ),
    ]
