# Generated by Django 4.1.7 on 2023-04-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_teachersnew_subject_teachersnew_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teachersnew",
            old_name="subject",
            new_name="subjects",
        ),
    ]
