# Generated by Django 4.1.7 on 2023-04-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_teachersectionsubject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachersnew",
            name="subjects",
        ),
    ]
